import type { Product, Category, Brand, Testimonial, Offer, BlogPost } from '@/types';

/** Fallback data when API is unavailable (matches seed.sql samples) */
export const MOCK_CATEGORIES: Category[] = [
  { id: '1', name: 'Gaming Laptops', slug: 'gaming', icon: '🎮', description: 'High-performance gaming', sort_order: 1, created_at: '' },
  { id: '2', name: 'Office & Business', slug: 'office', icon: '💼', description: 'Professional laptops', sort_order: 2, created_at: '' },
  { id: '3', name: 'Student Laptops', slug: 'student', icon: '📚', description: 'Affordable for students', sort_order: 3, created_at: '' },
  { id: '4', name: 'Ultrabooks', slug: 'ultrabooks', icon: '✨', description: 'Thin and premium', sort_order: 4, created_at: '' },
  { id: '5', name: 'Refurbished', slug: 'refurbished', icon: '🔄', description: 'Quality refurbished', sort_order: 5, created_at: '' },
];

export const MOCK_BRANDS: Brand[] = [
  { id: '1', name: 'Dell', slug: 'dell', logo_url: '', created_at: '' },
  { id: '2', name: 'HP', slug: 'hp', logo_url: '', created_at: '' },
  { id: '3', name: 'Lenovo', slug: 'lenovo', logo_url: '', created_at: '' },
  { id: '4', name: 'ASUS', slug: 'asus', logo_url: '', created_at: '' },
  { id: '5', name: 'Apple', slug: 'apple', logo_url: '', created_at: '' },
];

export const MOCK_PRODUCTS: Product[] = [
  {
    id: '1',
    name: 'Dell Inspiron 15 3520',
    slug: 'dell-inspiron-15-3520',
    brand_id: '1',
    category_id: '3',
    processor: 'Intel Core i5-1235U (12th Gen)',
    ram: '8 GB DDR4',
    storage: '512 GB SSD',
    display_size: '15.6" FHD',
    graphics: 'Intel UHD Graphics',
    os: 'Windows 11 Home',
    price: 42999,
    sale_price: 38999,
    images: ['https://images.unsplash.com/photo-1593642632559-0c6d3fc62b89?w=800'],
    specs: {},
    description: 'Perfect everyday laptop for students with 12th Gen Intel Core i5.',
    in_stock: true,
    featured: true,
    warranty: '1 Year Dell Warranty',
    condition: 'like-new',
    created_at: '',
    updated_at: '',
    brand: { id: '1', name: 'Dell', slug: 'dell', logo_url: '', created_at: '' },
    category: { id: '3', name: 'Student Laptops', slug: 'student', icon: '📚', description: '', sort_order: 3, created_at: '' },
  },
  {
    id: '2',
    name: 'HP Pavilion Gaming 15',
    slug: 'hp-pavilion-gaming-15',
    brand_id: '2',
    category_id: '1',
    processor: 'AMD Ryzen 5 5600H',
    ram: '16 GB DDR4',
    storage: '512 GB SSD',
    display_size: '15.6" FHD 144Hz',
    graphics: 'NVIDIA GTX 1650 4GB',
    os: 'Windows 11 Home',
    price: 59999,
    sale_price: 54999,
    images: ['https://images.unsplash.com/photo-1603302576837-37561b2e2302?w=800'],
    specs: {},
    description: 'Entry-level gaming laptop with 144Hz display and dedicated GPU.',
    in_stock: true,
    featured: true,
    warranty: '1 Year HP Warranty',
    condition: 'excellent',
    created_at: '',
    updated_at: '',
    brand: { id: '2', name: 'HP', slug: 'hp', logo_url: '', created_at: '' },
    category: { id: '1', name: 'Gaming Laptops', slug: 'gaming', icon: '🎮', description: '', sort_order: 1, created_at: '' },
  },
  {
    id: '3',
    name: 'Lenovo IdeaPad Slim 3',
    slug: 'lenovo-ideapad-slim-3',
    brand_id: '3',
    category_id: '3',
    processor: 'AMD Ryzen 5 5500U',
    ram: '8 GB DDR4',
    storage: '512 GB SSD',
    display_size: '15.6" FHD',
    graphics: 'AMD Radeon Graphics',
    os: 'Windows 11 Home',
    price: 34999,
    sale_price: 31999,
    images: ['https://images.unsplash.com/photo-1496181133206-80ce9b88a853?w=800'],
    specs: {},
    description: 'Lightweight and affordable — ideal for students and everyday use.',
    in_stock: true,
    featured: true,
    warranty: '1 Year Lenovo Warranty',
    condition: 'like-new',
    created_at: '',
    updated_at: '',
    brand: { id: '3', name: 'Lenovo', slug: 'lenovo', logo_url: '', created_at: '' },
    category: { id: '3', name: 'Student Laptops', slug: 'student', icon: '📚', description: '', sort_order: 3, created_at: '' },
  },
];

export const MOCK_TESTIMONIALS: Testimonial[] = [
  {
    id: '1',
    name: 'Rahul Sharma',
    rating: 5,
    text: 'Best laptop shop in Sirsa! Got a Dell Inspiron at an amazing price. Genuine products with warranty.',
    avatar_url: null,
    location: 'Sirsa',
    verified: true,
    created_at: '',
  },
  {
    id: '2',
    name: 'Priya Verma',
    rating: 5,
    text: 'Bought a gaming laptop for my brother. Great guidance from the team and quick WhatsApp support.',
    avatar_url: null,
    location: 'Hisar',
    verified: true,
    created_at: '',
  },
  {
    id: '3',
    name: 'Amit Kumar',
    rating: 5,
    text: 'Refurbished MacBook in excellent condition. Saved ₹30,000 compared to new. Highly recommended!',
    avatar_url: null,
    location: 'Fatehabad',
    verified: true,
    created_at: '',
  },
];

const futureDate = (days: number) => new Date(Date.now() + days * 86400000).toISOString();

export const MOCK_OFFERS: Offer[] = [
  {
    id: '1',
    title: 'Summer Sale 🔥',
    description: 'Get up to ₹10,000 off on selected gaming laptops. Limited time offer!',
    discount_type: 'flat',
    discount_value: 10000,
    valid_from: new Date().toISOString(),
    valid_until: futureDate(30),
    banner_image: 'https://images.unsplash.com/photo-1607082349566-187342175e2f?w=1200',
    product_ids: [],
    active: true,
    created_at: '',
  },
  {
    id: '2',
    title: 'Student Special 📚',
    description: 'Extra 5% discount for students on all laptops. Show valid college ID.',
    discount_type: 'percentage',
    discount_value: 5,
    valid_from: new Date().toISOString(),
    valid_until: futureDate(90),
    banner_image: 'https://images.unsplash.com/photo-1522202176988-66273c2fd55f?w=1200',
    product_ids: [],
    active: true,
    created_at: '',
  },
  {
    id: '3',
    title: 'Refurbished Deals',
    description: 'Premium refurbished laptops starting at just ₹14,999. Warranty included!',
    discount_type: 'special',
    discount_value: null,
    valid_from: new Date().toISOString(),
    valid_until: futureDate(60),
    banner_image: 'https://images.unsplash.com/photo-1484788984921-03950022c9ef?w=1200',
    product_ids: [],
    active: true,
    created_at: '',
  },
  {
    id: '4',
    title: 'MacBook Special',
    description: 'MacBook Air M1 now available at unbeatable prices. Limited stock!',
    discount_type: 'flat',
    discount_value: 8000,
    valid_from: new Date().toISOString(),
    valid_until: futureDate(15),
    banner_image: 'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=1200',
    product_ids: [],
    active: true,
    created_at: '',
  },
];

export const MOCK_BLOG_POSTS: BlogPost[] = [
  {
    id: '1',
    title: 'Top 5 Best Laptops for Students in 2024 — Budget Guide',
    slug: 'best-laptops-for-students-2024',
    content: `<h2>Finding the Perfect Student Laptop</h2><p>Choosing the right laptop for college or school can be overwhelming. Here at Punjab Laptop Sirsa, we have helped thousands of students find their ideal laptop within budget.</p><h3>1. Dell Inspiron 15 3520</h3><p>Starting at ₹38,999 — 12th Gen Intel Core i5, 8GB RAM, and 512GB SSD for effortless academic work.</p><h3>2. HP 14s</h3><p>At ₹29,499 — compact, lightweight, perfect for note-taking and light coding.</p><h3>3. Acer Aspire 5</h3><p>Best bang for your buck at ₹39,999 with backlit keyboard and IPS display.</p><h3>Visit Us</h3><p>Shop No. 52, New M.C. Market, Sirsa — best prices with warranty on every purchase.</p>`,
    excerpt: 'A comprehensive guide to the best budget laptops for students in 2024. Find the perfect laptop for college under ₹45,000.',
    cover_image: 'https://images.unsplash.com/photo-1522202176988-66273c2fd55f?w=1200',
    author: 'Punjab Laptop Sirsa',
    tags: ['students', 'budget', 'guide'],
    published: true,
    published_at: new Date(Date.now() - 5 * 86400000).toISOString(),
    created_at: '',
    updated_at: '',
  },
  {
    id: '2',
    title: 'Gaming Laptops Under ₹60,000 — Best Picks in Sirsa',
    slug: 'gaming-laptops-under-60000',
    content: `<h2>Gaming on a Budget</h2><p>You don't need to spend a fortune to enjoy modern games. These picks under ₹60,000 deliver excellent performance for GTA V, Valorant, and Fortnite.</p><h3>HP Pavilion Gaming 15 — ₹49,999</h3><p>AMD Ryzen 5 + GTX 1650 handles most games at medium-high settings.</p><h3>Acer Nitro 5 — ₹59,999</h3><p>RTX 3050 Ti with 144Hz display for competitive gaming.</p><h3>Why Buy From Us?</h3><p>We personally test every gaming laptop. Competitive Sirsa pricing with genuine warranty.</p>`,
    excerpt: 'Discover the best gaming laptops under ₹60,000 at Punjab Laptop Sirsa. GTX 1650 and RTX 3050 options with warranty.',
    cover_image: 'https://images.unsplash.com/photo-1603302576837-37561b2e2302?w=1200',
    author: 'Punjab Laptop Sirsa',
    tags: ['gaming', 'budget', 'guide'],
    published: true,
    published_at: new Date(Date.now() - 3 * 86400000).toISOString(),
    created_at: '',
    updated_at: '',
  },
  {
    id: '3',
    title: 'New vs Refurbished Laptops — Which Should You Buy?',
    slug: 'new-vs-refurbished-laptops-guide',
    content: `<h2>Making the Smart Choice</h2><p>At Punjab Laptop Sirsa, we offer both new and refurbished laptops. The right choice depends on your needs and budget.</p><h3>When to Buy New</h3><p>Choose new when you need the latest processor, longest warranty, or current-model features.</p><h3>When to Buy Refurbished</h3><p>Refurbished is ideal when budget matters. Every unit passes battery, display, keyboard, and port testing.</p><h3>Our Promise</h3><p>Minimum 6 months warranty, certified testing, genuine software, and satisfaction support.</p>`,
    excerpt: 'Learn the differences between new and refurbished laptops. Make an informed decision at Punjab Laptop Sirsa.',
    cover_image: 'https://images.unsplash.com/photo-1484788984921-03950022c9ef?w=1200',
    author: 'Punjab Laptop Sirsa',
    tags: ['refurbished', 'guide', 'tips'],
    published: true,
    published_at: new Date(Date.now() - 7 * 86400000).toISOString(),
    created_at: '',
    updated_at: '',
  },
  {
    id: '4',
    title: 'Laptop Care Tips — Make Your Machine Last Years',
    slug: 'laptop-care-tips',
    content: `<h2>Essential Laptop Maintenance</h2><p>A few simple habits can extend your laptop's life and keep performance smooth.</p><h3>Keep It Cool</h3><p>Use on hard surfaces, clean vents monthly, and avoid blocking fans during gaming.</p><h3>Battery Health</h3><p>Avoid draining to 0% daily. Keep charge between 20–80% when possible for longer battery life.</p><h3>Software Hygiene</h3><p>Update Windows regularly, use antivirus, and uninstall unused programs.</p><h3>Professional Service</h3><p>Visit Punjab Laptop Sirsa for cleaning, thermal paste replacement, and genuine spare parts in Sirsa.</p>`,
    excerpt: 'Expert laptop care tips from Punjab Laptop Sirsa. Keep your laptop fast, cool, and reliable for years.',
    cover_image: 'https://images.unsplash.com/photo-1588872657578-7efd1f1555ed?w=1200',
    author: 'Punjab Laptop Sirsa',
    tags: ['tips', 'care', 'maintenance'],
    published: true,
    published_at: new Date(Date.now() - 10 * 86400000).toISOString(),
    created_at: '',
    updated_at: '',
  },
  {
    id: '5',
    title: 'Best Budget Laptops in Sirsa — Under ₹35,000',
    slug: 'best-budget-laptops-sirsa',
    content: `<h2>Maximum Value, Minimum Spend</h2><p>Looking for a reliable laptop without breaking the bank? These are our top picks under ₹35,000 available today in Sirsa.</p><h3>HP 14s — ₹29,499</h3><p>Lightweight daily driver for browsing, documents, and online classes.</p><h3>Lenovo IdeaPad Slim 3 — ₹31,999</h3><p>AMD Ryzen 5 power in a slim chassis — excellent for multitasking.</p><h3>Why Punjab Laptop?</h3><p>Wholesale and retail pricing, verified condition grading, and WhatsApp support at 9991020143.</p>`,
    excerpt: 'Best budget laptops under ₹35,000 in Sirsa. Verified stock, warranty, and student-friendly pricing.',
    cover_image: 'https://images.unsplash.com/photo-1496181133206-80ce9b88a853?w=1200',
    author: 'Punjab Laptop Sirsa',
    tags: ['budget', 'students', 'sirsa'],
    published: true,
    published_at: new Date(Date.now() - 2 * 86400000).toISOString(),
    created_at: '',
    updated_at: '',
  },
];
